let time,
    fontFamily = 'Consolas, Arial, Helvetica, sans-serif',
    storageKey = 'my-font-family-selector::' + location.host + location.pathname;

/**
 * Some specified element is generated by JavaScript,
 *     necessary to wait for the generation before updating font family.
 */
new Promise(function (resolve, reject) {
    let query = {};
    query[storageKey] = null;
    window['chrome']['storage']['local'].get(query, function (result) {
        if (result[storageKey]) {
            const getElement = function () {
                const $el = window['jQuery'](result[storageKey]);
                if ($el.length > 0) {
                    resolve($el);
                } else {
                    time = setTimeout(getElement, 100);
                }
            };
            getElement();
        } else {
            reject();
        }
    });
}).then(function ($el) {
    $el.css('font-family', fontFamily);
}).catch(function () {
});

/**
 * Message is sent from popup.js, callbacks are defined in popup-callbacks.js
 */
window['chrome']['runtime']['onMessage'].addListener(function (request, sender, sendResponse) {
    if (window['popupCallbacks'][request.command] !== undefined) {
        sendResponse(window['popupCallbacks'][request.command].apply(null, request.params));
    }
});
